"""
Layer 1 retrieval: subsystem localization.

Given a feature description, use keyword overlap with the pre-built subsystem map
to identify candidate directories. Zero LLM calls at query time.

The subsystem map was generated by subsystem_mapper.py and contains:
  {dir_path: {name, description, keywords}}
"""

import re
from typing import Optional


def _tokenize(text: str) -> set[str]:
    """
    Tokenize text into lowercase words.
    Handles both Chinese (character n-grams) and English (word split).
    """
    # English words
    english = set(re.findall(r'[a-zA-Z][a-zA-Z0-9_]*', text.lower()))
    # Chinese characters and 2-grams
    chinese_chars = re.findall(r'[\u4e00-\u9fff]', text)
    chinese = set(chinese_chars)
    # Also add adjacent pairs as bigrams
    for i in range(len(chinese_chars) - 1):
        chinese.add(chinese_chars[i] + chinese_chars[i + 1])
    return english | chinese


def locate_subsystems(
    feature_desc: str,
    subsystem_map: dict,
    top_k: int = 4,
    fallback_all: bool = True,
) -> list[str]:
    """
    Match feature description against subsystem keywords to identify candidate directories.

    Args:
        feature_desc: user's feature description string
        subsystem_map: loaded from subsystem_map.json
        top_k: maximum number of subsystems to return
        fallback_all: if True and no subsystem matched, return all directory paths

    Returns:
        list of directory paths (strings, e.g. ["src/storage", "src/executor"])
    """
    query_tokens = _tokenize(feature_desc)

    scores: list[tuple[int, str]] = []

    for dir_path, info in subsystem_map.items():
        # Collect all text for this subsystem entry
        keywords: list[str] = info.get("keywords", [])
        description: str = info.get("description", "")
        name: str = info.get("name", "")

        candidate_tokens = _tokenize(" ".join(keywords) + " " + description + " " + name)

        # Score = number of overlapping tokens
        overlap = len(query_tokens & candidate_tokens)
        if overlap > 0:
            scores.append((overlap, dir_path))

    scores.sort(key=lambda x: x[0], reverse=True)
    matched = [path for _, path in scores[:top_k]]

    if not matched and fallback_all:
        # No match — return all known paths so retrieval proceeds over full index
        matched = list(subsystem_map.keys())

    return matched


def filter_functions_by_subsystem(
    function_index: dict,
    candidate_dirs: list[str],
) -> dict:
    """
    Return a sub-dict of function_index containing only functions whose
    file path starts with one of the candidate directories.

    Args:
        function_index: full function index {func_name: {file, ...}}
        candidate_dirs: directory paths returned by locate_subsystems()

    Returns:
        filtered function index (same structure, subset of entries)
    """
    if not candidate_dirs:
        return function_index

    result = {}
    for func_name, info in function_index.items():
        file_path = info.get("file", "")
        if any(file_path.startswith(d.rstrip("/") + "/") or file_path.startswith(d.rstrip("/"))
               for d in candidate_dirs):
            result[func_name] = info
    return result
